name: MMOCraft
version: 1.3.1-R2_b1
main: com.scizzr.bukkit.mmocraft.MMOCraft
authors:
  - Scizzr
softdepend: [Vault]
commands:
  class:
    description: Set class or get class information
    usage:
      /<command> [class]        : Get information about a class
      /<command> set [class]    : Set class
  mmo:
    description: MMO commands
    usage:
      /<command> stats [player] : View player information
  aids:
    description: List aids
    usage:
      /<command>                : View your aids
  pets:
    description: List pets
    usage:
      /<command>                : View your pets
  eff:
    description: Sound effects
    usage:
      /<command> [type] [name]  : Play an effect
permissions:
  